[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "oldest-supported-numpy",
    "Cython",
]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v --nbmake --disable-warnings"
testpaths = [
    "tests",
    "book/example",
]
