package:
  name: larch
  version: "5.7.1"

source:
  path: ../

build:
  number: 1
  skip: True  # [py<37]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"   # [not osx]
    - "export SDKROOT=$(xcrun --sdk macosx --show-sdk-path) && export LDFLAGS=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib && {{ PYTHON }} -m pip install . --no-deps -vv"  # [osx]

requirements:

  build:
    - python {{ python }}
    - pip
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy', upper_bound='1.22') }}

  host:
    - python {{ python }}
    - pip
    - llvm-openmp  # [osx]
    - cython >=0.29
    - {{ pin_compatible('numpy', upper_bound='1.22') }}

  run:
    - python {{ python }}
    - ipython >=7.1
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy', upper_bound='1.22') }}
    - scipy >=1.1
    - pandas >=0.24,<1.5
    - pytables >=3.4.4  # https://github.com/conda-forge/pytables-feedstock/issues/31
    - blosc >=1.14.3
    - matplotlib >=3.0
    - networkx >=2.4
    - tqdm >=4.28.1
    - cloudpickle >=0.6.1
    - appdirs >=1.4
    - docutils >=0.13.1
    - jinja2 >=2.10
    - beautifulsoup4 >=4.6.3
    - lxml >=4.2.5
    - seaborn >=0.9.0
    - scikit-learn >=0.21
    - joblib
    - pytest >=4.0
    - xmle >=0.1.3
    - addicty >=2022.2.1
    - pyyaml
    - pillow
    - xlsxwriter
    - openpyxl
    - pydot
    - pyarrow
    - numba
    - xarray
    - sharrow >=2.0

test:
  source_files:
    - tests
    - book
    - pyproject.toml
  imports:
    - larch
  commands:
    - pytest
    - pytest --pyargs larch

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest
    - pytest-regressions
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - geopandas
    - nbmake
    - tabulate
    - zarr
    - altair
    - apsw

about:
  home: https://larch.newman.me
  license: GPLv3
  summary: 'Discrete Choice Modeling in Python'
  license_family: GPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
