name: dev-docs

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment: developer
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        environment-file: environments/development.yml
        python-version: 3.9
        activate-environment: development
        auto-activate-base: false
        auto-update-conda: false
    - name: Install sharrow
      run: |
        git clone https://github.com/ActivitySim/sharrow.git
        cd sharrow
        python -m pip install --no-deps -e .
    - name: Install larch
      run: |
        python -m pip install --no-deps -e .
    - name: Conda checkup
      run: |
        conda info -a
        conda list
    - name: Build the docs
      run: |
        python book/_scripts/hide_test_cells.py
        python book/_scripts/developer_doc_title.py
        jb build book
    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Token is created automatically by Github Actions, no other config needed
        publish_dir: ./book/_build/html
    - name: Push to External GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./book/_build/html
        external_repository: jpndashdash/larch-dev-docs
        destination_dir: latest
